chaijs/chai-http

lib/request.js
Hi @keithamus,
Thanks for your help - pull when you have a chance...
We expose the `superagent.Request` object in `chai-http/lib/request.js`.
To use:
```js
chai.use(require('chai-http'));
// This line now works!
require('superagent-proxy')(chai.request);
chai
.request('http://external.example.com')
.get('/')
.proxy('http://my-proxy.example.org:80')
.end(function (res) {
});
```
See, bug #27 for more discussion.
Yours,
Nick
=> Bug #27, Add support for proxy servers via "superagent-proxy"

README.md
The Query parameters should be passed as an object not as key/value parameter-pairs. Took me quite a while to figure this out, that's why I've updated the README
=> Clarify the usage of query parameters in README

lib/request.js, package.json
I've updated Superagent to Version 1.0.x (https://github.com/chaijs/chai-http/issues/34) - it works on my project and also the tests passed
Additionally last time I was changing the README, I edited it directly but now I noticed that it's actually built from the comment, and I've applied the same changes about query parameters also in the comments so that the README is built properly
=> Superagent to Version 1.0.x + Update query parameter usage also in comment

lib/http.js
There are two tests that [have been failing](https://travis-ci.org/chaijs/chai-http/jobs/105547469#L259-L271).  The `param` method wasn't working when called without a value. For example:  `expect(req).to.have.param('orderby')`
=> Fixed two failing tests

Makefile, README.md, dist/chai-http.js, docs/header.md, index.html, lib/http.js, lib/net.js, lib/request.js, package.json, test/bootstrap/index.js, test/http.js, test/request.js
This PR adds browser support (issue https://github.com/chaijs/chai-http/issues/68).  All tests pass in Node and in all modern web browsers (Chrome, Firefox, Safari, Opera, Internet Explorer, and Edge)
`make` or `make bundle` will create a browser-compatible bundle, via  [browserify](http://browserify.org/)
`npm start` will build the browser bundle and then start an HTTP server at http://localhost:8080, so you can run the tests in your web browser(s).
Most of the existing tests worked fine in browsers without any changes.  A few of the assertion tests required minor changes to use [SuperAgent's properties/methods](https://visionmedia.github.io/superagent/#response-properties) instead of [Node's properties/methods](https://nodejs.org/api/http.html#http_response_statuscode).  The SuperAgent …
=> Browser support

.travis.yml, lib/request.js, package.json, test/request.js
I hate 5 minutes to update all of the outdated packages in this repo. It means we have a few breaking changes here: namely no more support for Node <4, and also any breaking changes qs or superagent have.
Luckily it means we get to delete some of our code, as superagent now supports promises directly 😄 
@meeber happy to take a look?
FYI this closes #96 #94 #89 #88 #87 #84 #82 #74 #54
=> Update all the things

MAINTAINERS
apparently the MAINTAINERS file is case-sensitive.  Who knew?  🙃
=> fixed case-sensitivity typo in the MAINTAINERS file

README.md
The formatting was affected by the lack of space above the heading, this seemed to be fine in Github flavoured markdown but whatever http://chaijs.com is using didn't like it.
=> Fix formatting for Chai website docs

lib/request.js
This clarifies how to send form data. `.field()` works for multi-part forms, but according to the [SuperAgent documentation](https://visionmedia.github.io/superagent/#post-/-put-requests) `.send()` should be used to send the post data as `application/x-www-form-urlencoded`. This addresses issue #86. There is an older pull request by @BenAychh, but it modified the README.md file directly. According to the discussion, the README.md file is generated based on request.js, and so the documentation should be modified here.
=> Update request.js documentation

README.md
Hello everyone,
I realized that there was some bad placed/missing semicolons on README
There are more semicolons missing from previous examples (ex: Line 70) but I think that it make sense to not add an semicolon there to indicate that the user should keep chaining methods.
If you think that we should have semicolons for those previous examples too, please let me know to update this PR.
Thank you all ❤️
=> Fix some bad semicolon placements at README.md

README.md
Many of the other examples show `.not` variations, updated `.redirect` to be consistent
=> Add to.not.redirect example to README

package.json, test/http.js
Chai v4.0 causes some tests to fail due to the change of `deep.property` to `nested.property`, and also because a couple of assertion error messages changed slightly. This PR fixes the broken tests.
DO NOT MERGE YET. This PR will be updated once Chai v4.0 is officially released.
=> Update for Chai v4.0

README.md
Just dropped the "login" keyword in the guide to make it easier to discover by new users searching for it.
=> Make it easier to find out how to login during tests

README.md
expect function was being used in readme examples without ever explicitly defining expect
=> Issue #172: readme can be misleading

package.json
the license property of the package.json was misspelled, making it hard for tools like license-crawler and the likes to fetch the used license
=> chore(package): fixed license typo

lib/request.js, test/request.js
Test and changes to request to allow `.keepOpen()` request to actually close, fixes #189.
FYI Side Note - I had to disable posttest `script` during local development as it causes `npm test` to fail (I have no token) with:
```sh
> if [ -z "$COVERALLS_REPO_TOKEN" ]; then cat coverage/lcov.info | coveralls; fi
/Users/marty/dev/chai-http/node_modules/coveralls/bin/coveralls.js:18
throw err;
^
Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}
```
=> Enable closing after "keepOpen()" has been called

README.md, lib/http.js, test/http.js, types/index.d.ts
=> configures redirectTo to accept regex

.travis.yml
From #248, I've added my personal access token ([scoped just to `public_repo`](https://github.com/semantic-release/github#github-authentication)) but happy to change it. Might also considering rotating the NPM token.
=> ci: add secure variables to release stage

.npmrc, .releaserc.json, .travis.yml, package.json
More (and hopefully last) tweaks for semantic releasing:
- builds in the release step, and [adds the files to the release commit](https://github.com/semantic-release/git#usage).
- removes `.npmrc` so we don't need an `NPM_TOKEN` for every stage, and the [npm semantic-release plugin will dynamically create one](https://github.com/semantic-release/npm#semantic-releasenpm) when needed.
I've figured out why the `NPM_TOKEN` isn't be correctly set as well: previously we were using the Travis npm deploy, where just the API key was encrypted, but now we need it to be an environment variable with a name. I don't have publish rights to npm, but can someone generate a token and then encrypt it like this?
```sh
travis encrypt NPM_TOKEN=$NPM_TOKEN
``` 
Also, can we remove the Sauce [travis env …
=> ci: build before release, commit assets, remove .npmrc

README.md, lib/http.js, package-lock.json, package.json, test/http.js, types/index.d.ts
=> Add matcher to check for charset.

package-lock.json, package.json
Update superagent dependency to 6.1.0 in order to address the `DeprecationWarning` referenced in #262
Cookiejar also must be updated to be in sync with superagent.
=> Update superagent to ^6.1.0

.github/workflows/ci.yml
The last master run did not publish because of a faulty `if` clause.
see: https://github.com/chaijs/chai-http/actions/runs/596951264
see: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsif
=> ci: correctly template github event in `if` condition for release

.github/workflows/ci.yml
It's `github.event_name`, not `github.event` :man_facepalming:.
=> ci: use correct `event_name` property

.github/workflows/ci.yml
Aaaaand anotha one. Could do caching, but would just like this to work first. Guess this is what happens when we update the CI and release system and don't use it for two years, hah.
Ran the build locally after a clean `npm ci` install and it succeeded.
https://github.com/chaijs/chai-http/runs/1972788417
=> ci: install node deps before release

README.md
chai-http supports Authorization with Bearer Token. But, this feature is not mentioned anywhere on the site or readme file. 
This would be useful for many developers & Tester.
Ref: https://github.com/chaijs/chai-http/blob/master/dist/chai-http.js#L3359
=> Added auth example with Bearer Token

.github/workflows/ci.yml
Following from https://github.com/chaijs/chai-http/pull/285 this uses a custom API token with Repo/Packages scopes to handle releases, separate from the `github_token`.
=> Update CI release token

.github/workflows/ci.yml, README.md, package-lock.json, package.json
We're currently overriding the NPM version in the release step, which I think is the reason the CI release is failing yet again (though further along, again). https://github.com/chaijs/chai-http/runs/1979587374#step:5:93
Since npm@6 is now legacy and no longer installed w/ any LTS node, we should upgrade it anyway, so might as well be now. 
Since node 8 is EOL and we're trying to do a major release anyway, also might as well happen now.
Also:
* upgrades all the semantic-release plugins which, for the most part just had Node support breaking changes, and all others were for specific configs that chai-http is not using
* reformats some README docs
=> feat: drop support for node < 10

README.md
=> docs: add badges to the README

package-lock.json, package.json, test/http.js, test/request.js
- update `superagent` to latest version to fix security vulnerabilities
- update `qs` and `cookiejar` to the latest version
- Lock `@types/superagent` to `4.1.13` due to the failing typescript compiler
- I think we should drop node < 16 support (because they are EOL) and for further dependency updates)
- The test `npm test` were failing before and after the dependency updates
- Should I provide a follow-up PR and try to fix these issues
- Also, I didn't update all dependencies in the PR yet, because nearly all of them have breaking changes
- Should I provide a follow-up PR and update all these dependencies?
- I noticed, that in the `ci.yml` file there are some old node versions, which were scheduled for removal, but are still in there
- Should I update them?
This PR addresses the …
=> Dependency updates to fix security vulnerabilities

.releaserc.json
To fix pipeline issues stopping chai-http from pushing new release.
Likely issue with the JSON parser not liking the single quotes, so just switched the quotes around alpha to double quotes.
=> Fix: Pipeline push not working

README.md
Fix #326 - readme: add how to import chai 5 and use chaiHttp 4
=> Fix #326 - readme: add how to import chai 5 and use chaiHttp 4

.editorconfig, .prettierrc, eslint.config.mjs, index.js, lib/http.js, lib/net.js, lib/request.js, package-lock.json, package.json, test/bootstrap/index.js, test/http.js, test/request.js, types/index.d.ts, types/test.ts
Hi,
Based on https://github.com/chaijs/chai-http/pull/310#discussion_r1589951063 here is a follow-up PR with prettier and a simple eslint configuration for styling the project files
Can we do a **5.0.0 release** after this, so the NPM package corresponds to the current readme? Could be confusing otherwise. (the pipeline seems broken, issue seems like a wrong NPM token, therefore the 401 error, FWIK)
Changes:
- add eslint, eslint-plugin-mocha, prettier
- run prettier on all files
- update a re-export of `is-ip`
First step for #318
/cc @43081j
=> feat: add prettier and eslint

eslint.config.mjs, index.js, lib/http.js, package-lock.json, package.json, test/bootstrap/index.js, test/http.js, test/request.js
=> fix(esm): main resolution extension required

README.md
Updates the usage to make it clear you can now import `request` rather than using `chai.request`.
cc @koddsson 
I'll do a new release once this merges
=> docs: update wording on usage

README.md, types/index.d.ts
Updates the types to export a `request` object, and also updates the readme to prefer `request.*` rather than `chai.request.*`.
=> fix: update docs and types to expose `request`

README.md
This fixes two small typos in the README, both related to how the correct usage for passing a web server app to the library now uses `request.execute()` instead of `request()`.
1. You pass an `app` to `request.execute()` now, not just `request`
2. `request` isn't a function any more, so the Promise reference should simply refer to it as `request`
=> fix some readme typos

package-lock.json, package.json
We expose superagent's types in our own types, so this should be a production dependency. Otherwise, we will cause errors in the typescript builds of consumers (unless they skip lib check).
It does mean we add an unnecessary dependency for non-ts people, but there's not any simple way around that.
Fixes #346
=> fix: add superagent types as prod dependency

eslint.config.mjs, package-lock.json, package.json, test/bootstrap/index.js, test/request.js
Long ago it seems we stopped testing in a browser, so this removes the associated switches in the test files and moves to a node-only suite.
Meanwhile, this moves to using c8 for coverage and also reworks the tests to hit a local server rather than a real one (previously was hitting `chaijs.com` and another domain or two which changed underneath it over time).
CI is failing in main right now because of this. It was relying on external web servers for the tests to pass, and they have since changed the responses it was asserting against
@koddsson could you possibly take a look at this?
the diff is worthless i think, you're better off reading the new file by itself
=> test: rework tests to node-only

package.json
We mistakenly left `import` in our export map, which means CJS consumers can't `require` chai-http right now.
This should fix it.
=> fix: use default export
